<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-0AP94ACM" failures="1" tests="1" name="Test(failed)" time="0.123" errors="0" timestamp="2023-03-28T12:56:44 IST">
  <testcase classname="com.trello.qspiders.learntestng.GroupA" name="nameA" time="0.034">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.trello.qspiders.learntestng.GroupA.nameA(GroupA.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- nameA -->
  <testcase classname="com.trello.qspiders.learntestng.GroupA" name="nameB" time="0.0">
    <ignored/>
  </testcase> <!-- nameB -->
  <testcase classname="com.trello.qspiders.learntestng.GroupA" name="nameC" time="0.0">
    <ignored/>
  </testcase> <!-- nameC -->
</testsuite> <!-- Test(failed) -->
